shuosc/SHU-Bachelor-Thesis-Typst

LICENSE

update Apache License

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md

The effect is similar to [SHU-Bachelor-Thesis-OSC](https://github.com/shuosc/SHU-Bachelor-Thesis-OSC).

[FEATURE] Update Issue Template and PR Template

---

layouts/mainmatter.typ
pages/cover.typ
style/figures.typ
style/heading.typ
template/thesis.typ

fix the bug of chapter counters dosen‘t reset the index of image/algorithm/table
- closes #26 
The Bug
After Fixed

fix the bug of chapter counters dosen‘t reset the index of image/algorithm/table

---

.gitattributes
.github/workflows/pr-to-universe.yml
.github/workflows/scripts/typship-login-universe.expect
.github/workflows/scripts/typship-push-universe.expect
.typstignore
LICENSE
typst.toml

Update an Github Action for automatically create an PR to typist universe.
The action is triggered when pushing tag `v*.*.*`, and the tag must align with the package version.
- resolves #23 
| Software     | Version |
| ------------ | ------- |
| Typst        |    0.13.10     |
**Local Workflow has been proven to take effect.** See:  
- https://github.com/jamesnulliu/xy-typst-shu-thesis/actions/runs/14520909139
- Which creates [this PR](https://github.com/typst/packages/pull/2216) .
For the repo maintainers, after merging this PR, you should push a tag align with the current package version to test this action.

[FEATURE] Update Github Action: Create PR to Typist Universe

---

assets/citation-style.csl
layouts/doc.typ
pages/bib.typ
template/thesis.typ
typst.toml

1. 统一了字母和汉字的上下边缘高度，修复了数字和字母的悬浮问题（之前的数字和字母会向上偏移5%）；
2. 现在可以自己选择注释使用上角标还是正常格式；

[FEATURE] Update v0.1.4

---

pages/outline.typ
style/heading.typ
template/thesis.typ

将正文部分的引用设置为"正文1.1"；附录部分的引用设置为对应的标题。
closes #32

[FIX] fix the wrong prefix of referencing contents.

---

a.typ
layouts/doc.typ
lib.typ
pages/bib.typ
style/figures.typ
template/thesis.typ

1. Add more citation styles and examples.
2. Fix some small bugs: table alignment and page id.
| Software     | Version |
| ------------ | ------- |
| Typst        | 0.13.10 |

[FEATURE] Add more citation styles and examples

---

pages/bib.typ
template/ref.bib
template/thesis.typ

支持多语言的文章引用（即正确显示类似于et al.和等.的引用)
closes #35
| Software     | Version |
| ------------ | ------- |
| Typst        |0.13.10|

[FEATURE] support multiple languages citation

---

template/thesis.typ

支持绘制多个子图，并添加了相应的代码和引用方式
无
| Software      | Version |
| ------------- | ------- |
| Typst         | 0.13.10 |

[FEATURE] support subfigures

---

style/heading.typ

Fixed the bug where the line spacing of chapter headings did not meet the requirements.
- closes #39 
| Software      | Version |
| ------------- | ------- |
| Typst         | 0.13.10 |

[FIX] Fix the bug of chaper line spacing

---

layouts/doc.typ
layouts/mainmatter.typ
lib.typ
pages/cover.typ
pages/declare.typ
style/figures.typ
template/thesis.typ

[style] Formalize thesis.typ
重写了figures模块
1. 移除了tablex中的`colnums`参数，增加了其它可选参数
2. 允许图表没有`label-name`
3. 增加了`imagx`和`subimagex`函数，便于图片的创建
重构量较大，需要测试后合入

[REFACTOR] Rewrite all figures

---

layouts/doc.typ
layouts/mainmatter.typ
style/figures.typ
style/font.typ
template/thesis.typ

[FEATURE] Support different math level and fix image caption

---

pages/cover.typ
pages/declare.typ
style/heading.typ

1. 修改了一些样式差异；
2. 修复了封面表格偏移的问题；

[FIX] Fix the style of some headings and tables

---

pages/outline.typ
template/thesis.typ

[FEATURE] Allow the user to choose whether the content is compact or not

---

layouts/doc.typ
pages/cover.typ
pages/declare.typ
pages/outline.typ
style/font.typ
template/thesis.typ

1. 修复了样式问题
2. 修复了字体显示的问题，严格按照拉丁文优先Times New Roman，中文优先微软字体，而后系统字体

[FIX] Fix some style problems

---

layouts/doc.typ
style/figures.typ

[FIX] Fix the dulplicate caption in subfigures reference

---

style/figures.typ
style/heading.typ

[Fix] Fix counter problem for equations

---

pages/acknowledgement.typ
pages/cover.typ

1. 修复了封面页面的逗号下沉问题
2. 修复了致谢页面尾部多空格的问题

[FIX] Fix style problems

---

layouts/doc.typ
lib.typ
pages/abstract.typ
pages/acknowledgement.typ
pages/cover.typ
pages/outline.typ
style/figures.typ
template/thesis.typ

* 更正了封面背景图片的位置和论文题目的字号
* 优化了封面信息的对齐和布局方式
* 提供了修改封面中论文题目线长的参数
* 调整了页眉线的粗细
* 增加了摘要文本和关键词之间的空行
* 更正了英文摘要中冒号的使用
* 增加了目录页二级标题与三级标题的行距
* 增加了子图中序号与标题之间的空格
* 增加了致谢文本和落款之间的空行

[FIX] improve formatting and visualization

---

layouts/doc.typ
layouts/mainmatter.typ
lib.typ
pages/abstract.typ
pages/acknowledgement.typ
pages/cover.typ
pages/declare.typ
pages/outline.typ
style/figures.typ
style/font.typ
style/heading.typ
template/thesis.typ

[FEAT] Support setting fonts by users

---

style/figures.typ

1. 修复了超过三页的表格导致续表错误的问题；
2. 移除了不必要的参数

[FIX] Fix figure bugs

---

lib.typ

[FIX] Support low version
